server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javastudy?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: select 1
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      filter:
        stat:
          log-slow-sql: true
          db-type: mysql
          slow-sql-millis: 2000
      stat-view-servlet:
        login-password: druid
        login-username: druid
        allow: 127.0.0.1
        url-pattern: /druid/*
  thymeleaf:
    cache: false
    mode: LEGACYHTML


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.zhezii.model
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true

